import { Equipment } from './types';

export const initialEquipments: Equipment[] = [
  {
    id: 'motor-001',
    name: 'Motor',
    type: 'Rotating Machinery',
    criticalityLevel: 'Most critical',
    status: 'Active',
    description: 'Main drive motor for critical process',
    lastUpdated: '2025-12-12T14:30:00',
    parameters: [
      {
        id: 'param-001',
        name: 'Vibration DS',
        unit: 'mm/s',
        lowerThreshold: 0.5,
        upperThreshold: 4.5,
        dataType: 'Numeric',
        alertPriority: 'High',
        monitoringEnabled: true,
        remarks: 'Drive end bearing vibration',
      },
      {
        id: 'param-002',
        name: 'Vibration NDS',
        unit: 'mm/s',
        lowerThreshold: 0.5,
        upperThreshold: 4.5,
        dataType: 'Numeric',
        alertPriority: 'High',
        monitoringEnabled: true,
        remarks: 'Non-drive end bearing vibration',
      },
      {
        id: 'param-003',
        name: 'Temperature Bearing - DS',
        unit: '°C',
        lowerThreshold: 30,
        upperThreshold: 80,
        dataType: 'Numeric',
        alertPriority: 'Critical',
        monitoringEnabled: true,
        remarks: '',
      },
      {
        id: 'param-004',
        name: 'Temperature Bearing - NDS',
        unit: '°C',
        lowerThreshold: 30,
        upperThreshold: 80,
        dataType: 'Numeric',
        alertPriority: 'Critical',
        monitoringEnabled: true,
        remarks: '',
      },
      {
        id: 'param-005',
        name: 'Current',
        unit: 'Ampere (A)',
        lowerThreshold: 10,
        upperThreshold: 100,
        dataType: 'Numeric',
        alertPriority: 'Medium',
        monitoringEnabled: true,
        remarks: 'Motor current draw',
      },
      {
        id: 'param-006',
        name: 'Speed',
        unit: 'RPM',
        lowerThreshold: 1000,
        upperThreshold: 3000,
        dataType: 'Numeric',
        alertPriority: 'Medium',
        monitoringEnabled: true,
        remarks: 'Rotational speed',
      },
    ],
  },
  {
    id: 'plc-001',
    name: 'PLC',
    type: 'Electrical',
    criticalityLevel: 'High',
    status: 'Active',
    description: 'Programmable Logic Controller for process automation',
    lastUpdated: '2025-12-12T14:30:00',
    parameters: [
      {
        id: 'param-101',
        name: 'CPU Temperature',
        unit: '°C',
        lowerThreshold: 20,
        upperThreshold: 60,
        dataType: 'Numeric',
        alertPriority: 'High',
        monitoringEnabled: true,
        remarks: '',
      },
      {
        id: 'param-102',
        name: 'Power Supply Voltage',
        unit: 'V',
        lowerThreshold: 22,
        upperThreshold: 26,
        dataType: 'Numeric',
        alertPriority: 'Critical',
        monitoringEnabled: true,
        remarks: '24V DC nominal',
      },
      {
        id: 'param-103',
        name: 'Communication Status',
        unit: 'Boolean',
        lowerThreshold: null,
        upperThreshold: null,
        dataType: 'Boolean',
        alertPriority: 'Critical',
        monitoringEnabled: true,
        remarks: 'Online/Offline status',
      },
      {
        id: 'param-104',
        name: 'Scan Time',
        unit: 'ms',
        lowerThreshold: 0,
        upperThreshold: 100,
        dataType: 'Numeric',
        alertPriority: 'Medium',
        monitoringEnabled: true,
        remarks: 'Program scan cycle time',
      },
    ],
  },
  {
    id: 'drive-001',
    name: 'XYZ Drive',
    type: 'Electrical',
    criticalityLevel: 'High',
    status: 'Active',
    description: 'Variable Frequency Drive for motor control',
    lastUpdated: '2025-12-12T14:30:00',
    parameters: [
      {
        id: 'param-201',
        name: 'Output Frequency',
        unit: 'Hz',
        lowerThreshold: 0,
        upperThreshold: 60,
        dataType: 'Numeric',
        alertPriority: 'Medium',
        monitoringEnabled: true,
        remarks: '',
      },
      {
        id: 'param-202',
        name: 'Output Current',
        unit: 'Ampere (A)',
        lowerThreshold: 5,
        upperThreshold: 150,
        dataType: 'Numeric',
        alertPriority: 'High',
        monitoringEnabled: true,
        remarks: '',
      },
      {
        id: 'param-203',
        name: 'DC Bus Voltage',
        unit: 'V',
        lowerThreshold: 500,
        upperThreshold: 700,
        dataType: 'Numeric',
        alertPriority: 'Critical',
        monitoringEnabled: true,
        remarks: 'Internal DC link voltage',
      },
      {
        id: 'param-204',
        name: 'Heat Sink Temperature',
        unit: '°C',
        lowerThreshold: 30,
        upperThreshold: 85,
        dataType: 'Numeric',
        alertPriority: 'High',
        monitoringEnabled: true,
        remarks: '',
      },
      {
        id: 'param-205',
        name: 'Drive Status',
        unit: 'Text',
        lowerThreshold: null,
        upperThreshold: null,
        dataType: 'Text',
        alertPriority: 'Critical',
        monitoringEnabled: true,
        remarks: 'Running/Stopped/Fault',
      },
    ],
  },
];
